### ISSUE TITLE
feat: add setup for a docker compose fille for a postgresql db

### ISSUE THREAD

**Issue by yehezkieldio** [yehezkieldio/callisto#3]
~As the title suggests.

The PostgreSQL credentials should be from `.env`.

`docker-compose.yml`
```yml
services:
    project-name-postgres:
        image: postgres
        container_name: project-name-postgres
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: ${DOCKER_DATABASE_USER}
            POSTGRES_PASSWORD: ${DOCKER_DATABASE_PASSWORD}
            POSTGRES_DB: ${DOCKER_DATABASE_NAME}
        volumes:
            - ./postgresql-data:/var/lib/postgresql/data
volumes:
    postgresql-data:
```

`.env`
```
DOCKER_DATABASE_USER=postgres
DOCKER_DATABASE_PASSWORD=postgres
DOCKER_DATABASE_NAME=project-name

DATABASE_URL=postgres://postgres:postgres@localhost:5432/project-name
```
